/*
  Warnings:

  - Added the required column `updated_at` to the `peserta_didik` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "dapodik"."peserta_didik" ADD COLUMN     "alasan_layak_pip" TEXT,
ADD COLUMN     "alasan_menolak_kip" TEXT,
ADD COLUMN     "alat_transportasi_id_str" TEXT,
ADD COLUMN     "cita_cita" TEXT,
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dusun" TEXT,
ADD COLUMN     "foto" TEXT,
ADD COLUMN     "hobi" TEXT,
ADD COLUMN     "jarak_rumah_ke_sekolah_km" TEXT,
ADD COLUMN     "jenis_tinggal_id_str" TEXT,
ADD COLUMN     "jumlah_saudara_kandung" INTEGER,
ADD COLUMN     "kabupaten_kota" TEXT,
ADD COLUMN     "kebutuhan_khusus_ayah" TEXT,
ADD COLUMN     "kebutuhan_khusus_ibu" TEXT,
ADD COLUMN     "kecamatan" TEXT,
ADD COLUMN     "lingkar_kepala" INTEGER,
ADD COLUMN     "nama_di_kip" TEXT,
ADD COLUMN     "no_registrasi_akta_lahir" TEXT,
ADD COLUMN     "no_seri_skhun" TEXT,
ADD COLUMN     "no_ujian_nasional" TEXT,
ADD COLUMN     "no_wa" TEXT,
ADD COLUMN     "no_wa_ayah" TEXT,
ADD COLUMN     "no_wa_ibu" TEXT,
ADD COLUMN     "no_wa_wali" TEXT,
ADD COLUMN     "npsn_sekolah_asal" TEXT,
ADD COLUMN     "paud_formal" TEXT,
ADD COLUMN     "paud_non_formal" TEXT,
ADD COLUMN     "pendidikan_ayah_id_str" TEXT,
ADD COLUMN     "pendidikan_ibu_id_str" TEXT,
ADD COLUMN     "pendidikan_wali_id_str" TEXT,
ADD COLUMN     "penghasilan_ayah_id_str" TEXT,
ADD COLUMN     "penghasilan_ibu_id_str" TEXT,
ADD COLUMN     "penghasilan_wali_id_str" TEXT,
ADD COLUMN     "provinsi" TEXT,
ADD COLUMN     "qr_token" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'Aktif',
ADD COLUMN     "status_wali" TEXT NOT NULL DEFAULT 'Tidak',
ADD COLUMN     "telegram_chat_id" TEXT,
ADD COLUMN     "telegram_token" TEXT,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "waktu_tempuh_menit" TEXT,
ALTER COLUMN "agama_id" SET DATA TYPE TEXT,
ALTER COLUMN "kewarganegaraan" SET DEFAULT 'Indonesia',
ALTER COLUMN "pekerjaan_ayah_id" SET DATA TYPE TEXT,
ALTER COLUMN "pekerjaan_ibu_id" SET DATA TYPE TEXT,
ALTER COLUMN "pekerjaan_wali_id" SET DATA TYPE TEXT,
ALTER COLUMN "kurikulum_id" SET DATA TYPE TEXT;
