-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "dapodik";

-- CreateTable
CREATE TABLE "dapodik"."tanah" (
    "id_tanah" UUID NOT NULL,
    "jenis_prasarana_id" INTEGER NOT NULL,
    "sekolah_id" UUID NOT NULL,
    "id_hapus_buku" TEXT,
    "kepemilikan_sarpras_id" TEXT,
    "kd_kl" TEXT,
    "kd_satker" TEXT,
    "kd_brg" TEXT,
    "nup" TEXT,
    "kode_eselon1" TEXT,
    "nama_eselon1" TEXT,
    "kode_sub_satker" TEXT,
    "nama_sub_satker" TEXT,
    "nama" TEXT NOT NULL,
    "panjang" DOUBLE PRECISION,
    "lebar" DOUBLE PRECISION,
    "nilai_perolehan_aset" DECIMAL(65,30),
    "kode_wilayah" TEXT NOT NULL,
    "alamat_jalan" TEXT NOT NULL,
    "rt" TEXT,
    "rw" TEXT,
    "nama_dusun" TEXT,
    "desa_kelurahan" TEXT,
    "kode_pos" TEXT,
    "lintang" DECIMAL(65,30),
    "bujur" DECIMAL(65,30),
    "tgl_mutasi_keluar" TIMESTAMP(3),
    "batas" TEXT,
    "ket_tanah" TEXT,
    "luas" DECIMAL(65,30),
    "luas_lahan_tersedia" DECIMAL(65,30),
    "no_sertifikat_tanah" TEXT,
    "asal_data" TEXT,
    "create_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_update" TIMESTAMP(3) NOT NULL,
    "soft_delete" TEXT,
    "last_sync" TIMESTAMP(3),
    "updater_id" UUID,
    "jenis_prasarana_id_str" TEXT,
    "kode_wilayah_str" TEXT,
    "sekolah_id_str" TEXT,
    "vld_count" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "tanah_pkey" PRIMARY KEY ("id_tanah")
);

-- CreateTable
CREATE TABLE "dapodik"."bangunan" (
    "id_bangunan" UUID NOT NULL,
    "jenis_prasarana_id" INTEGER NOT NULL,
    "sekolah_id" UUID NOT NULL,
    "id_tanah" UUID NOT NULL,
    "ptk_id" UUID,
    "id_hapus_buku" TEXT,
    "kepemilikan_sarpras_id" TEXT,
    "kd_kl" TEXT,
    "kd_satker" TEXT,
    "kd_brg" TEXT,
    "nup" INTEGER,
    "kode_eselon1" TEXT,
    "nama_eselon1" TEXT,
    "kode_sub_satker" TEXT,
    "nama_sub_satker" TEXT,
    "nama" TEXT NOT NULL,
    "panjang" DOUBLE PRECISION,
    "lebar" DOUBLE PRECISION,
    "nilai_perolehan_aset" DECIMAL(65,30),
    "jml_lantai" TEXT,
    "thn_dibangun" TEXT,
    "luas_tapak_bangunan" DECIMAL(65,30),
    "vol_pondasi_m3" DECIMAL(65,30),
    "vol_sloop_kolom_balok_m3" DECIMAL(65,30),
    "panj_kudakuda_m" DECIMAL(65,30),
    "vol_kudakuda_m3" DECIMAL(65,30),
    "panj_kaso_m" DECIMAL(65,30),
    "panj_reng_m" DECIMAL(65,30),
    "luas_tutup_atap_m2" DECIMAL(65,30),
    "kd_satker_tanah" TEXT,
    "nm_satker_tanah" TEXT,
    "kd_brg_tanah" TEXT,
    "nm_brg_tanah" TEXT,
    "nup_brg_tanah" TEXT,
    "tgl_sk_pemakai" DATE,
    "tgl_hapus_buku" DATE,
    "ket_bangunan" TEXT,
    "asal_data" TEXT,
    "create_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_update" TIMESTAMP(3) NOT NULL,
    "soft_delete" TEXT,
    "last_sync" TIMESTAMP(3),
    "updater_id" UUID,
    "jenis_prasarana_id_str" TEXT,
    "id_tanah_str" TEXT,
    "sekolah_id_str" TEXT,
    "vld_count" INTEGER NOT NULL DEFAULT 0,
    "nilai_kerusakan" DECIMAL(65,30),
    "kriteria_kerusakan" TEXT,

    CONSTRAINT "bangunan_pkey" PRIMARY KEY ("id_bangunan")
);

-- CreateTable
CREATE TABLE "dapodik"."ruang" (
    "id_ruang" UUID NOT NULL,
    "jenis_prasarana_id" INTEGER NOT NULL,
    "sekolah_id" UUID NOT NULL,
    "parent_id_ruang" UUID,
    "id_bangunan" UUID NOT NULL,
    "asal_data" TEXT,
    "kd_ruang" TEXT,
    "nm_ruang" TEXT NOT NULL,
    "lantai" TEXT,
    "panjang" DOUBLE PRECISION,
    "lebar" DOUBLE PRECISION,
    "reg_pras" TEXT,
    "kapasitas" TEXT,
    "luas_ruang" DOUBLE PRECISION,
    "luas_plester_m2" DECIMAL(65,30),
    "luas_plafon_m2" DECIMAL(65,30),
    "luas_dinding_m2" DECIMAL(65,30),
    "luas_daun_jendela_m2" DECIMAL(65,30),
    "luas_daun_pintu_m2" DECIMAL(65,30),
    "panj_kusen_m" DECIMAL(65,30),
    "luas_tutup_lantai_m2" DECIMAL(65,30),
    "panj_inst_listrik_m" DECIMAL(65,30),
    "jml_inst_listrik" TEXT,
    "panj_inst_air_m" DECIMAL(65,30),
    "jml_inst_air" TEXT,
    "panj_drainase_m" DECIMAL(65,30),
    "luas_finish_struktur_m2" DECIMAL(65,30),
    "luas_finish_plafon_m2" DECIMAL(65,30),
    "luas_finish_dinding_m2" DECIMAL(65,30),
    "luas_finish_kpj_m2" DECIMAL(65,30),
    "create_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_update" TIMESTAMP(3) NOT NULL,
    "soft_delete" TEXT,
    "last_sync" TIMESTAMP(3),
    "updater_id" UUID,
    "jenis_prasarana_id_str" TEXT,
    "id_bangunan_str" TEXT,
    "sekolah_id_str" TEXT,

    CONSTRAINT "ruang_pkey" PRIMARY KEY ("id_ruang")
);
