-- CreateTable
CREATE TABLE "dapodik"."gtks" (
    "ptk_id" UUID NOT NULL,
    "ptk_terdaftar_id" UUID,
    "tahun_ajaran_id" TEXT,
    "sekolah_id" UUID,
    "ptk_induk" TEXT,
    "kode" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Aktif',
    "sk_mengajar" TEXT,
    "qr_token" TEXT,
    "nama" TEXT NOT NULL,
    "jenis_kelamin" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" DATE,
    "nama_ibu_kandung" TEXT,
    "agama_id" TEXT,
    "agama_id_str" TEXT,
    "nuptk" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "npwp" TEXT,
    "nama_wajib_pajak" TEXT,
    "kewarganegaraan" TEXT DEFAULT 'ID',
    "status_perkawinan" TEXT,
    "nama_suami_istri" TEXT,
    "pekerjaan_suami_istri" TEXT,
    "jenis_ptk_id" TEXT,
    "jenis_ptk_id_str" TEXT,
    "jabatan_ptk_id" TEXT,
    "jabatan_ptk_id_str" TEXT,
    "status_kepegawaian_id" TEXT,
    "status_kepegawaian_id_str" TEXT,
    "nip" TEXT,
    "niy_nigk" TEXT,
    "nrg" TEXT,
    "sk_pengangkatan" TEXT,
    "tanggal_surat_tugas" DATE,
    "tmt_pengangkatan" DATE,
    "lembaga_pengangkat" TEXT,
    "sk_cpns" TEXT,
    "tmt_cpns" DATE,
    "tmt_pns" DATE,
    "sumber_gaji" TEXT,
    "lisensi_kepsek" BOOLEAN NOT NULL DEFAULT false,
    "nuks" TEXT,
    "keahlian_laboratorium" TEXT,
    "mampu_menangani_kebutuhan_khusus" TEXT,
    "keahlian_braille" BOOLEAN NOT NULL DEFAULT false,
    "keahlian_bahasa_isyarat" BOOLEAN NOT NULL DEFAULT false,
    "pendidikan_terakhir" TEXT,
    "bidang_studi_terakhir" TEXT,
    "pangkat_golongan_terakhir" TEXT,
    "rwy_pend_formal" JSONB,
    "rwy_kepangkatan" JSONB,
    "alamat_jalan" TEXT,
    "rt" TEXT,
    "rw" TEXT,
    "dusun" TEXT,
    "desa_kelurahan" TEXT,
    "kecamatan" TEXT,
    "kode_pos" TEXT,
    "lintang" DECIMAL(65,30),
    "bujur" DECIMAL(65,30),
    "no_telepon_rumah" TEXT,
    "no_hp" TEXT,
    "no_wa" TEXT,
    "email" TEXT,
    "foto" TEXT,
    "tandatangan" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "gtks_pkey" PRIMARY KEY ("ptk_id")
);
